smart_cv_server/smart_cv_server/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [

    path('admin/', admin.site.urls),

    # WEBSITE

    path('', include('src.apps.website.urls', namespace='website')),
    path('accounts/', include('src.apps.accounts.urls', namespace='accounts')),
    path('', include('src.apps.cv_resume.urls', namespace='cv_resume')),
    path('invitation_card/', include('src.apps.invitation_card.urls', namespace='invitation_card')),
    path('cover_letter/', include('src.apps.cover_letter.urls', namespace='cover_letter')),

    # API URL

    path('api/', include('src.api.urls', namespace='api'))

]

smart_cv_server/src/apps/accounts/urls.py
from django.conf import urls
from django.urls import path

from .views import SignInView, SignUpView, ProfileView

app_name = 'accounts'

urlpatterns = [
    path('signup', SignUpView.as_view(), name='signup'),
    path('signin', SignInView.as_view(), name='signin'),
    path('profile/', ProfileView.as_view(), name='profile')

]

smart_cv_server/src/apps/accounts/forms.py
# forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User


# SIGNIN FORM

class SigninForm(AuthenticationForm):
    username = forms.CharField(label="Username", max_length=30,
                               widget=forms.TextInput(attrs={'class': 'form-control', 'placeholder': 'Enter your username'}))
    password = forms.CharField(label="Password", max_length=30,
                               widget=forms.PasswordInput(attrs={'class': 'form-control', 'placeholder': 'Enter your password'}))
# SIGNUP FORM


class SignupForm(UserCreationForm):

    class Meta:
        model = User
        fields = ('username', 'password1', 'password2')

smart_cv_server/src/apps/accounts/views.py
# views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.urls import reverse_lazy
from django.views.generic import TemplateView
from django.views.generic.edit import CreateView
from django.contrib.auth import login, authenticate

from src.apps.accounts.forms import SignupForm, SigninForm


class SignInView(LoginView):
    form_class = SigninForm
    template_name = 'signin.html'
    success_url = reverse_lazy('....')


class SignUpView(CreateView):
    form_class = SignupForm
    template_name = 'signup.html'
    success_url = reverse_lazy('website:home')


class ProfileView(LoginRequiredMixin, TemplateView):
    template_name = 'name.html'

smart_cv_server/src/apps/accounts/templates/name.html
{% extends 'base.html' %}
{% block title %}
    Login
{%  endblock %}

{% block content %}
<form action="/your-name/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Submit">
</form>
{% endblock content %}

smart_cv_server/src/apps/accounts/templates/signin.html
{% extends 'base.html' %}
{% block title %}Login{% endblock %}
{% block content %}
<body>

<div class="container">
    <h2>Sign In</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Sign In</button>
    </form>

    <p> If not have an Account <a href="{% url 'accounts:signup' %}">Register First </a> </p>
</div>

</body>

{% endblock content %}

smart_cv_server/src/apps/accounts/templates/signup.html
{% extends 'base.html' %}
{% block title %} SiginUP{% endblock %}
{% block content %}
<body>

<div class="container">
    <h2>Sign Up</h2>
    <form method="post">
        {% csrf_token %}
        {{ form }}
        <button type="submit" class="btn btn-primary">Sign Up</button>
    </form>
</div>


</body>

{% endblock content %}